website/views.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    jsonify,
    redirect,
    url_for,
    session,
    abort,
)
from flask_login import login_required, current_user
from datetime import datetime, timezone, timedelta
from sqlalchemy.sql import func
import bleach

from . import db
from .models import Note, Tag
from .forms import NoteForm
from .constants import allowed_html_tags, allowed_attributes, styles


views = Blueprint("views", __name__)


def time_ago(date_modified):
    now = datetime.now(timezone.utc) # https://stackoverflow.com/a/25662061
    time_difference = now - date_modified.replace(tzinfo=timezone.utc) # we have to do this because func.now() does not contain any timezone info
    seconds_ago = (
        time_difference.total_seconds()
    )  # https://stackoverflow.com/questions/51652952/python-timedelta-seconds-vs-total-seconds
    if seconds_ago / 86400 >= 1:
        return ["day", int(seconds_ago / 86400)]
    elif seconds_ago / 3600 >= 1:
        return ["hour", int(seconds_ago / 3600)]
    else:
        return ["min", int(seconds_ago / 60)]


# inject tags to populate the sidebar tag filter thing
@views.context_processor
def inject_tags():
    available_tags = {}
    if current_user.is_authenticated:
        available_tags = (
            Tag.query.filter_by(user_id=current_user.id).order_by(Tag.order.asc()).all()
        )
    return dict(global_tags=available_tags)


@views.route("/", methods=["GET", "POST"])
def home():
    if current_user.is_authenticated:
        filtered_notes = []
        if request.args.get(
            "filter"
        ):  # hidden checkbox with name="filter" (this means that form was submitted and we are trying to find out if "filter" exists. If form was not submitted, filter would not exist)
            tags_id = request.args.getlist("filtered-tags")  # a list of tag IDs

            filtered_tags = []
            filtered_tags = Tag.query.filter(Tag.id.in_(tags_id)).all()
            if filtered_tags:  # != []
                session["filtered_tags_id"] = [
                    tag.id for tag in filtered_tags
                ]  # accessed in base.html
                session["filtered_tags_name"] = [
                    tag.name for tag in filtered_tags
                ]  # accessed in index.html
                session.modified = True

                # https://stackoverflow.com/questions/42334197/add-only-unique-values-to-a-list-in-python
                # filtered_notes = list(set(filtered_notes))

                filtered_notes = (
                    Note.query.join(Tag, Note.tags)
                    .filter(Tag.id.in_(session["filtered_tags_id"]))
                    .group_by(Note.id)
                    .having(
                        func.count(Tag.id.distinct())
                        == len(session["filtered_tags_id"])
                    )
                    .order_by(Note.date_modified.desc())
                    .all()
                )
                # this is how the query works, it's a little glonky but it works. if tags_id (which the user selected) is 1 and 2, the notes containing tags 1 and 2, notes containing 1 but not 2, notes containing 2 but not 1 and notes containing both 1 and 2 are filtered. (these notes can also contain other tags but since we filter only tags 1 and/or 2, the other tags are not chosen in the query). Then we group tags by the note. If the no. of tags in the note are greater than or equal to the tags in tags_id, those notes are filtered (having is filter for aggregate functions).
                # so for example, there is note-1-2, note-1-3, note-1, note-1-2-3.
                # Note-1-2 is selected because it has tags 1 and 2, which are in tags_id. The number of distinct tags in the note is 2, which is equal to the len of tags_id.
                # Note-1-3 is NOT selected because tag 3 is NOT in tags-id.
                # Note-1 is NOT selected - it passes the first filter because tag 1 is in tags_id. However it doesn't pass the 'having' because it only has 1 distinct tag.
                # Note-1-2-3 is selected because it has tags 1 and 2 which are in tags_id. The number of distinct tags in the note is also 2, because tag 3 is not in tags_id.
                # https://stackoverflow.com/questions/13349832/sqlalchemy-filter-to-match-all-instead-of-any-values-in-list
                # https://stackoverflow.com/questions/35414358/sqlalachmey-orm-filter-to-match-all-items-in-a-list-not-any
            else:
                session["filtered_tags_id"] = []
                session["filtered_tags_name"] = []
                session.modified = True
                # if filters were unselected, we got to reset the filters
                filtered_notes = (
                    Note.query.filter_by(user_id=current_user.id)
                    .order_by(Note.date_modified.desc())
                    .all()
                )

        elif session.get(
            "filtered_tags_id"
        ):  # for normal GET requests when form was not submitted, we check if there are any filtered_tags, if there are we continue to show them
            filtered_notes = (
                Note.query.join(Tag, Note.tags)
                .filter(Tag.id.in_(session["filtered_tags_id"]))
                .group_by(Note.id)
                .having(
                    func.count(Tag.id.distinct()) == len(session["filtered_tags_id"])
                )
                .order_by(Note.date_modified.desc())
                .all()
            )
        else:  # for scenarios when no filters are selected
            filtered_notes = (
                Note.query.filter_by(user_id=current_user.id)
                .order_by(Note.date_modified.desc())
                .all()
            )

        for note in filtered_notes:
            note.time_ago = time_ago(note.date_modified)
            note.date_created_strf = (
                note.date_created.replace(tzinfo=timezone.utc)
                .astimezone(tz=None)
                .strftime("%x")
            )  # ?? https://stackoverflow.com/questions/4563272/how-to-convert-a-utc-datetime-to-a-local-datetime-using-only-standard-library

        return render_template(
            "content/index.html", user=current_user, filtered_notes=filtered_notes
        )
    return render_template("landing.html", user=current_user)


@views.route("/note/new", methods=["GET", "POST"])
@views.route("/note/<note_id>", methods=["GET", "POST"])
@login_required
def note(note_id=None):
    user_tags = Tag.query.filter_by(user_id=current_user.id).all()
    form = NoteForm()
    if request.method == "GET":
        # retrieve all the info from the note db object and display it on the screen
        if note_id is None:
            new_note = Note()
            new_note.user_id = current_user.id
            db.session.add(new_note)
            db.session.commit()
            flash("note created", category="success")
            return redirect(url_for("views.note", note_id=new_note.id))
        else:
            current_note = Note.query.get_or_404(note_id)
            if (
                current_note.user_id == current_user.id
            ):  # very important (without this users can access other users' notes)
                note_tags = current_note.tags
                # form.note_body.data = (
                #     current_note.body
                # )  # pre-populate the form in the server first because {{ ckeditor.load() }} is a textarea and I can't insert anything in between <textarea></textarea> since there is no textarea yet before Jinja renders the template. I usually prefer populating in the HTML because it is easier to see and change
                return render_template(
                    "content/note.html",
                    user=current_user,
                    current_note=current_note,
                    js_note_tags=note_tags,  # tags belonging to the note
                    js_user_tags=user_tags,  # tags belonging to the user
                    form=form,
                )
            else:
                abort(404)

    elif form.validate_on_submit:
        # retrieve all the info from the form and save it to the db
        current_note = Note.query.get_or_404(note_id)
        current_note.tags.clear()  # remove all previously saved tags on the note
        tags_id = form.note_tags.data  # ['2,3,6']
        if (
            tags_id
        ):  # allow for when there are no tags because the code below assumes tags
            tags_id = tags_id.split(",")  # ['2','3','6'] (str)
            tags_id = [int(tag_id) for tag_id in tags_id]  # convert to int
            # I have to be clear about what I'm passing around. Append takes in the ORM object as the variable. So I can't append the id directly, such as, current_note.tags.id.append(tag) where tag is a int for the id. I have to query for the object before appending it.
            for tag_id in tags_id:
                tag = Tag.query.filter_by(id=tag_id).one_or_none()
                current_note.tags.append(tag)
        else:  # allow for when there were tags but user removes tags
            tags_id = []
            current_note.tags = tags_id
        current_note.title = form.note_title.data

        current_note.body_delta = bleach.clean(
            form.note_body_delta.data,
            tags=allowed_html_tags,
            attributes=allowed_attributes,
            css_sanitizer=styles,
        )
        # bleaching note_body_html because it is HTML that is displayed on index.HTML
        current_note.body_html = bleach.clean(
            form.note_body_html.data,
            tags=allowed_html_tags,
            attributes=allowed_attributes,
            css_sanitizer=styles,
        )

        current_note.body_text = form.note_body_text.data
        current_note.date_modified = func.now()
        # current_note.verified = True
        db.session.commit()
        flash("note saved", category="success")

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico' )}}"> 
    
    <link
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital@0;1&family=Tomorrow:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename ='css/style.css') }}"
    />

    <title>{% block title %}{% endblock %} | ByteMemo</title>
    {% block insert_head_here %}{% endblock %}
  </head>

  <body>
    {% if user.is_authenticated %}
    <div class="sidebar sidebar-with-tags" id="sidebar">
      <!-- id is targeted in the menu button -->
      <nav class="nav-top">
        <a href="/" id="logo"
          ><img 
            class="logo-light"
            src="{{ url_for('static', filename = '/img/logo.png')}}"
            type="button"
            title="homepage"
            alt="ByteMemo logo"
          />
          <img 
            class="logo-dark"
            src="{{ url_for('static', filename = '/img/logo-dark.png')}}"
            type="button"
            title="homepage"
            alt="ByteMemo logo"
          />ByteMemo</a
        >
        <div class="toolbar-tag">
          <span>Tags</span>
          <button
            type="button"
            title="remove filters"
            onclick="removeFilters(event)"
          >
            <i class="bx bx-eraser bx-md"></i>
          </button>
          <a href="/edit-tags" title="edit tags" type="button">
            <i class="bx bx-edit-alt bx-md"></i>
          </a>
        </div>
      </nav>
      <form
        action="{{ url_for('views.home') }}?filter=yes&"
        method="GET"
        class="sidebar-form"
        id="sidebar-form"
      >
        <input type="checkbox" name="filter" value="true" checked hidden />

        <!-- global_tags is from the context processor in views.py  -->
        {% for tag in global_tags %} {% if tag.user_id is sameas user.id %} {%
        if tag.level is sameas 1 %}
        <div class="sidebar-tags">
          <div class="tag-checkbox level-1">
            <input name="filtered-tags" value="{{tag.id}}"
            id="checkbox-{{tag.id}}" type="checkbox" {{ 'checked' if tag.id in
            session['filtered_tags_id'] }} />
            <!-- filtered_tags is from flask sessions  -->
            <label for="checkbox-{{tag.id}}">{{tag.name}}</label>
          </div>
          {% set parent = tag.id %} {% for tag in global_tags %} {% if
          tag.user_id is sameas user.id %} {% if tag.parent_tag is sameas parent
          %}
          <div class="tag-checkbox level-2">
            <input name="filtered-tags" value="{{tag.id}}"
            id="checkbox-{{tag.id}}" type="checkbox" {{ 'checked' if tag.id in
            session['filtered_tags_id'] }} />
            <!-- filtered_tags is from flask sessions  -->
            <label for="checkbox-{{tag.id}}">{{tag.name}}</label>
          </div>
          {% endif %} {% endif %} {% endfor %}
        </div>
        {% endif %} {% endif %} {% endfor %}
      </form>

      <button form="sidebar-form" type="submit">Select Tags</button>

      <nav class="nav-bottom">
        <button class="grid-1" type="button" id="js-popover-button">
          <i class="bx bx-cog bx-md bx-spin-hover"></i>Manage Account
        </button>
        <a class="grid-2" href="/logout">
          <i class="bx bx-log-out-circle bx-md"></i>Log Out</a
        >

        <label>
          <input type="checkbox" id="js-darkmode" />
          <i class="bx bxs-moon"></i>
          <i class="bx bxs-sun"></i>
          <span class="bg-toggle"></span>
        </label>
      </nav>
    </div>

    {% else %}
    <!-- this links to if user.is_authenticated -->
    <div class="sidebar" id="sidebar">
      <nav class="nav-top">
        <a href="/" id="logo"
          ><img 
            class="logo-light"
            src="{{ url_for('static', filename = '/img/logo.png')}}"
            type="button"
            title="homepage"
            alt="ByteMemo logo"
          />
          <img 
            class="logo-dark"
            src="{{ url_for('static', filename = '/img/logo-dark.png')}}"
            type="button"
            title="homepage"
            alt="ByteMemo logo"
          />ByteMemo</a
        >
        <span class="empty-space"></span>
      </nav>
      <nav class="nav-bottom">
        <a class="grid-1" href="/signup"
          ><i class="bx bx-user-circle bx-md"></i>Signup</a
        >
        <a class="grid-2" href="/login"
          ><i class="bx bx-log-in-circle bx-md"></i>Login</a
        >
        <label for="js-darkmode">
          <input type="checkbox" id="js-darkmode" />
          <i class="bx bxs-moon"></i>
          <i class="bx bxs-sun"></i>
          <span class="bg-toggle"></span>
        </label>
      </nav>
    </div>
    {% endif %}
    <!-- this links to if user.is_authenticated  -->

    <!-- menu button  -->
    <div class="menu-button-group">
      <a class="menu-button" href="#sidebar">
        <span>
          <i class="bx bx-chevrons-left bx-rotate-180" aria-hidden="true"></i>
          <i class="bx bx-chevrons-left" aria-hidden="true"></i>
        </span>
      </a>
      <a class="menu-button close" href="#close-sidebar"></a>
    </div>

    <!-- popover for manage account -->
    <div class="sidebar-popover" id="js-sidebar-popover" popover>
      <nav>
        <ul>
          <li>
            <a href="/account-settings">Account Settings</a>
          </li>
          <li>
            <a href="/update-profile">Update Profile</a>
          </li>
          <li>
            <a href="/change-password">Change Password</a>
          </li>
        </ul>
      </nav>
    </div>

    <!-- same thing as popover but using dialog for browsers which don't support popover -->
    <dialog class="sidebar-popover" id="js-sidebar-dialog">
      <nav>
        <ul>
          <li>
            <a href="/account-settings">Account Settings</a>
          </li>
          <li>
            <a href="/update-profile">Update Profile</a>
          </li>
          <li>
            <a href="/change-password">Change Password</a>
          </li>
        </ul>
      </nav>
    </dialog>

    <!-- display success/error flash messages  -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div class="banner-container" id="banner">
      <!-- the if else statements in div and i are 2 different ways to do the same thing in Jinja. The first one is the standard if. The second one is the inline if.  -->
      <div
        class="banner {% if category == 'error' %} error {% else %} success {% endif %}"
      >
        <i
          class="bx {{ 'bxs-error-circle' if category == 'error' else 'bxs-check-circle' }}"
        ></i>
        <div class="banner-message">{{ message }}</div>
        <button type="button" id="close-banner" onclick="deleteBanner(event)">
          <span>&times;</span>
        </button>
      </div>
    </div>
    {% endfor %} {% endif %} {% endwith %}

    {% block content %} {% endblock %}

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/index.js')}}"
    ></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/kute.js/2.0.0/kute.min.js"></script>

    {% block insert_script_here %}{% endblock %}
  </body>
</html>